API_KEY: "test_api_key"
vad:
  host: "localhost"
  port: 5001
  sample_rate: 16000
stt:
  host: "localhost"
  port: 5002
llm:
  host: "localhost"
  port: 5004
db:
  host: "localhost"
  port: 5003
tts:
  host: "localhost"
  port: 5005
call_development:
  endpoint: "development"

orchestrator:
  host: "0.0.0.0"
  port: 8000
  endpoint: "orchestrator"
  chunk_duration: 40
  sample_rate_ms: 8000

