API_KEY: "91a64066-74a1-4687-ae2c-122362469cc9"
vad:
  host: "0.0.0.0"
  port: 5001
  sample_rate: 16000
stt:
  host: "0.0.0.0"
  port: 5002
llm:
  host: "0.0.0.0"
  port: 5004
db:
  endpoint: "db"
  host: "0.0.0.0"
  port: 5003
tts:
  host: "0.0.0.0"
  port: 5005
call_development:
  endpoint: "development"

orchestrator:
  host: "0.0.0.0"
  port: 8000
  endpoint: "orchestrator"
  chunk_duration: 40
  sample_rate_ms: 8000
